# Generated by Django 2.1.11 on 2019-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("courses", "0005_auto_20190717_0827")]

    operations = [
        migrations.AlterUniqueTogether(
            name="persontitletranslation", unique_together=set()
        ),
        migrations.RemoveField(model_name="persontitletranslation", name="master"),
        migrations.RemoveField(model_name="person", name="first_name"),
        migrations.RemoveField(model_name="person", name="last_name"),
        migrations.RemoveField(model_name="person", name="person_title"),
        migrations.AddField(
            model_name="organizationpluginmodel",
            name="template",
            field=models.CharField(
                choices=[
                    ("courses/plugins/organization.html", "Default"),
                    ("courses/plugins/organization_small.html", "Small"),
                ],
                default="courses/plugins/organization.html",
                help_text="Optional template for custom look.",
                max_length=150,
                verbose_name="Template",
            ),
        ),
        migrations.DeleteModel(name="PersonTitle"),
        migrations.DeleteModel(name="PersonTitleTranslation"),
    ]
